# Generated by Django 5.0.2 on 2024-04-21 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='51dbc2', max_length=6),
        ),
        migrations.AlterField(
            model_name='refreshsession',
            name='refresh_token',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
