# Generated by Django 5.0.2 on 2024-03-11 20:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_useraccount_email_alter_useraccount_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='username',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(3, message='Имя пользователя должно содержать не менее 3 символов'), django.core.validators.MaxLengthValidator(5, message='Имя пользователя должно превышать 20 символов')]),
        ),
    ]
