# Generated by Django 5.0.2 on 2024-04-21 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_otptoken_otp_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='c8bbef', max_length=6),
        ),
        migrations.AlterField(
            model_name='refreshsession',
            name='refresh_token',
            field=models.CharField(max_length=400, unique=True),
        ),
    ]
