# Generated by Django 5.0.2 on 2024-05-27 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='18a912', max_length=6),
        ),
        migrations.CreateModel(
            name='BooksCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('authors', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('pdf_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.pdffile')),
            ],
        ),
    ]
